title: MU20 Haacht
description: >- # This is your site description
  MU20 Haacht Home Page 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mu20-haacht.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima # or any other theme
header_pages:
  - 2425/index.md
  - 2425/part1.md

# Architect
# Cayman
# Dinky
# Hacker
# Leap day
# Merlot
# Midnight
# Minima
# Minimal
# Modernist
# Slate
# Tactile
# Time machine

# remote_theme: pages-themes/modernist@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one